### PR TITLE
Include standard architecture

### PR DESCRIPTION
**Pull request by ody**
Steps towards finding parity between GCP and AWS implementations
	of the Terraform modules that back puppetlabs/autope

### CODE REVIEW

**Comment by ody** [comment]
Works in light testing, probably needs more validation. After this need to work on docs so they are equivalent to Google and add agent node deployment (which I only finished adding to Google this morning)

**Comment by timidri** [comment]
LGTM upon quick read through, do you need me to test anything @ody ?

**Comment by ody** [comment]
@timidri After further testing, I am happy and this can be merged

**Comment by ody** [comment]
Superseded by https://github.com/puppetlabs/terraform-aws-pe_arch/pull/2

**Pull request closed without merging**
